### ISSUE TITLE
FiskalyKassensichvSmaInvoke() cause crash. 

### ISSUE THREAD

**Issue by wei0121** [fiskaly/fiskaly-kassensichv-client-ios#1]
Hey there. 
I was trying to run the project with only changes the TSS UUID / Client UUID / API Key / API Secret. But the FiskalyKassensichvSmaInvoke() will cause the app crashed when passing the string `{\"method\":\"version\",\"jsonrpc\":\"2.0\"}` as params. 

Would be nice if some detail description could be added into framework explain what kind of string should be pass into the function here.

**Comment by prempador** [comment]
Hello, 
sorry for the late response but we are currently working on a functional client for iOS. 

Your Issue seems to be, because you didn't add the SmaFramework as a dependency. 

1. Select the project file from the project navigator on the left side of the project window.
 
2. Select the target for where you want to add frameworks in the project settings editor.
 
3. Select the “Build Phases” tab, and click the small triangle next to “Link Binary With Libraries” to view all of the frameworks in your application.
 
4. To Add frameworks, click the “+” below the list of frameworks.

5. Add Other - Add Files - Select extracted Sma.framework

Please tell me if that worked for you.

**Comment by wei0121** [comment]
Thank you prempador, Adding framework to the Link Binary with libraries fix the issue.
